### ISSUE TITLE
Wicket warnings in console logs

### ISSUE THREAD

**Issue by ilgrosso** [ilgrosso/oldSyncopeIdM#172]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on October 05, 2011 17:29:36_

What steps will reproduce the problem? 1. start console
2. watch console logs
3. click on any section ('Users', for example) What is the expected output? What do you see instead? No exceptions should be reported, while a WARN is shown, like as following.
Please note that this stacktrace is reported at every subsequent click on other sections as well.

This behavior seems to have been introduced when upgrading to Wicket 1.5 (see issue `#170` ). 

17:14:59.179 WARN  org.apache.wicket.util.lang.WicketObjects - Could not resolve class [css]
java.lang.ClassNotFoundException: css
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1678) ~[catalina.jar:7.0.22]
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1523) ~[catalina.jar:7.0.22]
        at java.lang.Class.forName0(Native Method) ~[na:1.6.0_26]
        at java.lang.Class.forName(Class.java:247) ~[na:1.6.0_26]
        at org.apache.wicket.application.AbstractClassResolver.resolveClass(AbstractClassResolver.java:110) ~[wicket-core-1.5.1.jar:1.5.1]
        at org.apache.wicket.util.lang.WicketObjects.resolveClass(WicketObjects.java:68) ~[wicket-core-1.5.1.jar:1.5.1]
        at org.apache.wicket.request.mapper.AbstractComponentMapper.getPageClass(AbstractComponentMapper.java:138) [wicket-core-1.5.1.jar:1.5.1]
        at org.apache.wicket.request.mapper.BookmarkableMapper.parseRequest(BookmarkableMapper.java:110) [wicket-core-1.5.1.jar:1.5.1]
        at org.apache.wicket.request.mapper.AbstractBookmarkableMapper.mapRequest(AbstractBookmarkableMapper.java:263) [wicket-core-1.5.1.jar:1.5.1]
        at org.apache.wicket.request.mapper.CompoundRequestMapper.mapRequest(CompoundRequestMapper.java:130) [wicket-request-1.5.1.jar:1.5.1]
        at org.apache.wicket.request.cycle.RequestCycle.resolveRequestHandler(RequestCycle.java:179) [wicket-core-1.5.1.jar:1.5.1]
        at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:204) [wicket-core-1.5.1.jar:1.5.1]
        at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:251) [wicket-core-1.5.1.jar:1.5.1]
        at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:162) [wicket-core-1.5.1.jar:1.5.1]
        at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:218) [wicket-core-1.5.1.jar:1.5.1]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) [catalina.jar:7.0.22]

_Original issue: http://code.google.com/p/syncope/issues/detail?id=171_

**Comment by ilgrosso** [comment]
_From [geer...@gmail.com](https://code.google.com/u/114467990039872453366/) on October 06, 2011 02:02:28_

The problem cause is the new way of bookmarkable pages in Wicket 1.5.
The Schema-page URL for example now looks like:
http://localhost:9080/syncope-console/wicket/bookmarkable/org.syncope.console.pages.Schema
instead of having everything as query parameters.
This breaks relative links from inline css (which was in place in BasePage.html)

I have resolved it by moving the css declarations into style_sy.css (and changing the relative paths).
(feel free to move them to another external css if that's more appropriate)

**Attachment:** [2011-10-06-issue-171.patch](http://code.google.com/p/syncope/issues/detail?id=171#hc1)

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on October 06, 2011 02:33:10_

This issue was closed by revision r1180 .

**Status:** Fixed

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on October 06, 2011 02:33:33_

It works great. Thanks Geert!
