### ISSUE TITLE
Console cannot create valid resource schema mapping

### ISSUE THREAD

**Issue by ilgrosso** [ilgrosso/oldSyncopeIdM#193]
_From [geer...@gmail.com](https://code.google.com/u/114467990039872453366/) on October 18, 2011 13:14:58_

What steps will reproduce the problem? 1. Create a resource
2. Tick checkboxes 'Account Id' and 'Password' to some fields within the tab 'schema mapping'
2a. Watch the 'External attributes' dropdown to be disabled
3. Try to synchronize from this resource What is the expected output? What do you see instead? Actually I do not expect anything, because it's an invalid situation: the user should be able to select an external attribute to be used as the account id or password.

But it is allowed anyway. If you synchronize now, the core will throw an exception when mapping the attributes:
13:03:37.186 ERROR org.syncope.core.scheduling.AbstractJob - Could not create user x
java.lang.NullPointerException: null
	at java.lang.String$CaseInsensitiveComparator.compare(String.java:1217) ~[na:1.6.0_26]
	at java.lang.String$CaseInsensitiveComparator.compare(String.java:1211) ~[na:1.6.0_26]
	at java.util.TreeMap.getEntryUsingComparator(TreeMap.java:351) ~[na:1.6.0_26]
	at java.util.TreeMap.getEntry(TreeMap.java:322) ~[na:1.6.0_26]
	at java.util.TreeMap.get(TreeMap.java:255) ~[na:1.6.0_26]
	at java.util.Collections$UnmodifiableMap.get(Collections.java:1282) ~[na:1.6.0_26]
	at org.identityconnectors.framework.common.objects.ConnectorObject.getAttributeByName(ConnectorObject.java:88) ~[framework-1.3.1.jar:na]
	at org.syncope.core.scheduling.SyncJob.getUserTO(SyncJob.java:164) ~[SyncJob.class:na]
	at org.syncope.core.scheduling.SyncJob.doExecute(SyncJob.java:386) ~[SyncJob.class:na]
	at org.syncope.core.scheduling.AbstractJob.execute(AbstractJob.java:96) [AbstractJob.class:na]

**Attachment:** [schemamapping.png](http://code.google.com/p/syncope/issues/detail?id=192)

_Original issue: http://code.google.com/p/syncope/issues/detail?id=192_

**Comment by ilgrosso** [comment]
_From [fabio.ma...@gmail.com](https://code.google.com/u/109095430973973917901/) on October 18, 2011 05:48:33_

The indicated situation is valid.
The problem is that there is a bug inside the class SyncJob introduced recently.

'Destination attribute' could be avoided in case of AccountId and Password because possible names are only __NAME__ and __PASSWORD__ respectively.

**Status:** Started  
  **Owner:** fabio.ma...@gmail.com

**Comment by ilgrosso** [comment]
_From [fabio.ma...@gmail.com](https://code.google.com/u/109095430973973917901/) on October 18, 2011 06:09:37_

This issue was closed by revision r1201 .

**Status:** Fixed

**Comment by ilgrosso** [comment]
_From [geer...@gmail.com](https://code.google.com/u/114467990039872453366/) on October 18, 2011 06:40:48_

Verified, it works. Thanks.
