### ISSUE TITLE
Stacktraces on stderr in default setup

### ISSUE THREAD

**Issue by ilgrosso** [ilgrosso/oldSyncopeIdM#202]
_From [geer...@gmail.com](https://code.google.com/u/114467990039872453366/) on November 01, 2011 13:46:40_

What steps will reproduce the problem? 1. start with a default setup (let Syncope create the schema upon startup)
2. create a connector instance
3. select the connector instance when creating a resource What is the expected output? What do you see instead? No exceptions in logs, let alone stderr.
However, several stacktraces are thrown, about syncPolicy, passwordPolicy and accountPolicy.

If those (default?) policies are required for normal operation, then they should be provided by the default setup, I would argue.

SEVERE: Servlet.service() for servlet [syncope-core-rest] in context with path [/syncope] threw exception [Request processing failed; nested exception is javassist.NotFoundException: No password policy found] with root cause
javassist.NotFoundException: No password policy found
	at org.syncope.core.rest.controller.PolicyController.getGlobalPasswordPolicy(PolicyController.java:188)
	at org.syncope.core.rest.controller.PolicyController$$FastClassByCGLIB$$bf8e6a66.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191)
	at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:688)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)

SEVERE: Servlet.service() for servlet [syncope-core-rest] in context with path [/syncope] threw exception [Request processing failed; nested exception is javassist.NotFoundException: No account policy found] with root cause
javassist.NotFoundException: No account policy found
	at org.syncope.core.rest.controller.PolicyController.getGlobalAccountPolicy(PolicyController.java:204)
	at org.syncope.core.rest.controller.PolicyController$$FastClassByCGLIB$$bf8e6a66.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191)

SEVERE: Servlet.service() for servlet [syncope-core-rest] in context with path [/syncope] threw exception [Request processing failed; nested exception is javassist.NotFoundException: No sync policy found] with root cause
javassist.NotFoundException: No sync policy found
	at org.syncope.core.rest.controller.PolicyController.getGlobalSyncPolicy(PolicyController.java:220)
	at org.syncope.core.rest.controller.PolicyController$$FastClassByCGLIB$$bf8e6a66.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191)

_Original issue: http://code.google.com/p/syncope/issues/detail?id=201_

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on November 08, 2011 07:46:08_

**Summary:** Stacktraces on stderr in default setup  
  **Status:** Started  
  **Owner:** mdisabat...@gmail.com  
  **Labels:** Milestone-Release-201112 Component-Logic Component-Persistence Source-trunk

**Comment by ilgrosso** [comment]
_From [mdisabat...@gmail.com](https://code.google.com/u/101550733072735377085/) on November 15, 2011 05:30:27_

Insert default policy for account, password and sync

**Attachment:** [2011-11-16-issue-201.patch](http://code.google.com/p/syncope/issues/detail?id=201#hc2)

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on November 16, 2011 06:55:35_

This issue was closed by revision r1255 .

**Status:** Fixed
