### ISSUE TITLE
Stacktrace with default Syncope Configuration

### ISSUE THREAD

**Issue by ilgrosso** [ilgrosso/oldSyncopeIdM#213]
_From [mdisabat...@gmail.com](https://code.google.com/u/101550733072735377085/) on November 18, 2011 15:52:04_

What steps will reproduce the problem? 1. click on Roles

What is the expected output?
An empty tree

What do you see instead?
Stacktrace

*** ./SyncopeSource/syncope-0.7/console/target/log/console.log ***
15:42:57.166 ERROR org.syncope.console.SyncopeRequestCycleListener - Exception found
org.apache.wicket.WicketRuntimeException: Can't instantiate page using constructor 'public org.syncope.console.pages.Roles(org.apache.wicket.request.mapper.parameter.PageParameters)' and argument ''. Might be it doesn't exist, may be it is not visible (public).
	at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:196) ~[wicket-core-1.5.2.jar:1.5.2]
	at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:77) ~[wicket-core-1.5.2.jar:1.5.2]
	at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:47) ~[wicket-core-1.5.2.jar:1.5.2]
	at org.apache.wicket.DefaultMapperContext.newPageInstance(DefaultMapperContext.java:103) ~[wicket-core-1.5.2.jar:1.5.2]
	at org.apache.wicket.request.handler.PageProvider.resolvePageInstance(PageProvider.java:264) ~[wicket-core-1.5.2.jar:1.5.2]
	at org.apache.wicket.request.handler.PageProvider.getPageInstance(PageProvider.java:165) ~[wicket-core-1.5.2.jar:1.5.2]
	at org.apache.wicket.request.handler.render.PageRenderer.getPage(PageRenderer.java:78) ~[wicket-core-1.5.2.jar:1.5.2]
	at org.apache.wicket.request.handler.render.WebPageRenderer.renderPage(WebPageRenderer.java:105) ~[wicket-core-1.5.2.jar:1.5.2]
	at org.apache.wicket.request.handler.render.WebPageRenderer.respond(WebPageRenderer.java:224) ~[wicket-core-1.5.2.jar:1.5.2]
	at org.apache.wicket.request.handler.RenderPageRequestHandler.respond(RenderPageRequestHandler.java:167) ~[wicket-core-1.5.2.jar:1.5.2]
	at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:750) ~[wicket-core-1.5.2.jar:1.5.2]
	at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64) ~[wicket-request-1.5.2.jar:1.5.2]
	at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:252) [wicket-core-1.5.2.jar:1.5.2]
	at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:209) [wicket-core-1.5.2.jar:1.5.2]
	at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:280) [wicket-core-1.5.2.jar:1.5.2]
	at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:162) [wicket-core-1.5.2.jar:1.5.2]
	at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:218) [wicket-core-1.5.2.jar:1.5.2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) [catalina.jar:7.0.22]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.22]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:224) [catalina.jar:7.0.22]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169) [catalina.jar:7.0.22]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [catalina.jar:7.0.22]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168) [catalina.jar:7.0.22]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100) [catalina.jar:7.0.22]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:929) [catalina.jar:7.0.22]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.22]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:405) [catalina.jar:7.0.22]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:964) [tomcat-coyote.jar:7.0.22]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:515) [tomcat-coyote.jar:7.0.22]
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:302) [tomcat-coyote.jar:7.0.22]
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) [na:1.6.0_29]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) [na:1.6.0_29]
	at java.lang.Thread.run(Thread.java:680) [na:1.6.0_29]
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.6.0_29]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39) ~[na:1.6.0_29]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27) ~[na:1.6.0_29]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513) ~[na:1.6.0_29]
	at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:173) ~[wicket-core-1.5.2.jar:1.5.2]
	... 32 common frames omitted
java.lang.StackOverflowError: null
	at java.util.Arrays.sort(Arrays.java:1210) ~[na:1.6.0_29]
	at java.util.Collections.sort(Collections.java:159) ~[na:1.6.0_29]
	at org.syncope.console.commons.RoleTreeBuilder.getChildRoles(RoleTreeBuilder.java:46) ~[RoleTreeBuilder.class:na]
	at org.syncope.console.commons.RoleTreeBuilder.populateSubtree(RoleTreeBuilder.java:56) ~[RoleTreeBuilder.class:na]
	at org.syncope.console.commons.RoleTreeBuilder.populateSubtree(RoleTreeBuilder.java:59) ~[RoleTreeBuilder.class:na]

**Attachment:** [content.xml](http://code.google.com/p/syncope/issues/detail?id=212)

_Original issue: http://code.google.com/p/syncope/issues/detail?id=212_

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on November 18, 2011 07:21:17_

**Status:** Started  
  **Owner:** chicchiricco  
  **Labels:** Milestone-Release-201112 Source-trunk Component-UI

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on November 18, 2011 07:22:09_

This issue was closed by revision r1259 .

**Status:** Fixed
