### ISSUE TITLE
Error in List User

### ISSUE THREAD

**Issue by ilgrosso** [ilgrosso/oldSyncopeIdM#221]
_From [mdisabat...@gmail.com](https://code.google.com/u/101550733072735377085/) on November 24, 2011 14:57:24_

What steps will reproduce the problem? 1. Click User/List 
2. Select email as an attribute to show
3. Create a user with an empty email field 

What is the expected output?
List of user.

What do you see instead?
Root cause:

java.lang.NullPointerException
at org.syncope.console.wicket.extensions.markup.html.repeater.data.table.UserAttrColumn.populateItem(UserAttrColumn.java:60)
at org.apache.wicket.extensions.markup.html.repeater.data.grid.AbstractDataGridView.populateItem(AbstractDataGridView.java:156)
at org.apache.wicket.markup.repeater.RefreshingView$1.newItem(RefreshingView.java:113)
at org.apache.wicket.markup.repeater.DefaultItemReuseStrategy$1.next(DefaultItemReuseStrategy.java:71)
at org.apache.wicket.markup.repeater.DefaultItemReuseStrategy$1.next(DefaultItemReuseStrategy.java:68)
at org.apache.wicket.markup.repeater.RefreshingView.addItems(RefreshingView.java:188)
at org.apache.wicket.markup.repeater.RefreshingView.onPopulate(RefreshingView.java:97)
at org.apache.wicket.markup.repeater.AbstractRepeater.onBeforeRender(AbstractRepeater.java:119)
at org.apache.wicket.markup.repeater.AbstractPageableView.onBeforeRender(AbstractPageableView.java:115)
at org.apache.wicket.Component.internalBeforeRender(Component.java:981)
at org.apache.wicket.Component.beforeRender(Component.java:1015)
at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1785)
at org.apache.wicket.Component.onBeforeRender(Component.java:3774)
at org.apache.wicket.Component.internalBeforeRender(Component.java:981)
at org.apache.wicket.Component.beforeRender(Component.java:1015)
at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1785)
at org.apache.wicket.Component.onBeforeRender(Component.java:3774)
at org.apache.wicket.Component.internalBeforeRender(Component.java:981)
at org.apache.wicket.Component.beforeRender(Component.java:1015)
at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1785)
at org.apache.wicket.Component.onBeforeRender(Component.java:3774)
at org.apache.wicket.Component.internalBeforeRender(Component.java:981)
at org.apache.wicket.Component.beforeRender(Component.java:1015)
at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1785)
at org.apache.wicket.Component.onBeforeRender(Component.java:3774)
at org.apache.wicket.Component.internalBeforeRender(Component.java:981)
at org.apache.wicket.Component.beforeRender(Component.java:1015)
at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1785)
at org.apache.wicket.Component.onBeforeRender(Component.java:3774)
at org.apache.wicket.Page.onBeforeRender(Page.java:823)
at org.apache.wicket.Component.internalBeforeRender(Component.java:981)
at org.apache.wicket.Component.beforeRender(Component.java:1015)
at org.apache.wicket.Component.internalPrepareForRender(Component.java:2184)
at org.apache.wicket.Page.internalPrepareForRender(Page.java:280)
at org.apache.wicket.Component.render(Component.java:2271)
at org.apache.wicket.Page.renderPage(Page.java:1035)

_Original issue: http://code.google.com/p/syncope/issues/detail?id=220_

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on November 24, 2011 05:58:45_

**Status:** Started  
  **Owner:** mdisabat...@gmail.com  
  **Labels:** Component-UI Milestone-Release-201112

**Comment by ilgrosso** [comment]
_From [mdisabat...@gmail.com](https://code.google.com/u/101550733072735377085/) on November 24, 2011 09:13:12_

Fixed UserAttrColumn. Check if field is present.

**Attachment:** [2011-11-23-issue-220.patch](http://code.google.com/p/syncope/issues/detail?id=220#hc2)

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on November 25, 2011 00:20:14_

This issue was closed by revision r1266 .

**Status:** Fixed
