### ISSUE TITLE
Stacktrace when creating user on default setup

### ISSUE THREAD

**Issue by ilgrosso** [ilgrosso/oldSyncopeIdM#227]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on November 30, 2011 17:09:10_

What steps will reproduce the problem? 1. Default setup as per http://wiki.syncope-idm.org/index.php?title=GettingStarted-SNAPSHOT (real world - MySQL)
2. Create an user as per http://wiki.syncope-idm.org/index.php?title=CallingRESTFromCommandLine What is the expected output? What do you see instead? *** /opt/syncope/log//core-rest.log ***
17:03:51.461 ERROR org.syncope.core.rest.controller.AbstractController - Exception thrown by REST methods
java.lang.NullPointerException: null
        at java.util.regex.Matcher.getTextLength(Matcher.java:1140) ~[na:1.6.0_26]
        at java.util.regex.Matcher.reset(Matcher.java:291) ~[na:1.6.0_26]
        at java.util.regex.Matcher.<init>(Matcher.java:211) ~[na:1.6.0_26]
        at java.util.regex.Pattern.matcher(Pattern.java:888) ~[na:1.6.0_26]
        at org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.replaceVariables(ResourceBundleMessageInterpolator.java:188) ~[hibernate-validator-4.2.0.Final.jar:4.2.0.Final]
        at org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.interpolateMessage(ResourceBundleMessageInterpolator.java:148) ~[hibernate-validator-4.2.0.Final.jar:4.2.0.Final]
        at org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.interpolate(ResourceBundleMessageInterpolator.java:112) ~[hibernate-validator-4.2.0.Final.jar:4.2.0.Final]
        at org.springframework.validation.beanvalidation.LocaleContextMessageInterpolator.interpolate(LocaleContextMessageInterpolator.java:49) ~[spring-context-3.0.6.RELEASE.jar:3.0.6.RELEASE]
        at org.hibernate.validator.engine.StandardValidationContext.createConstraintViolation(StandardValidationContext.java:49) ~[hibernate-validator-4.2.0.Final.jar:4.2.0.Final]
        at org.hibernate.validator.engine.ValidationContext.createConstraintViolations(ValidationContext.java:196) ~[hibernate-validator-4.2.0.Final.jar:4.2.0.Final]
        at org.hibernate.validator.engine.ConstraintTree.validateSingleConstraint(ConstraintTree.java:286) ~[hibernate-validator-4.2.0.Final.jar:4.2.0.Final]
        at org.hibernate.validator.engine.ConstraintTree.validateConstraints(ConstraintTree.java:153) ~[hibernate-validator-4.2.0.Final.jar:4.2.0.Final]
        at org.hibernate.validator.engine.ConstraintTree.validateConstraints(ConstraintTree.java:117) ~[hibernate-validator-4.2.0.Final.jar:4.2.0.Final]
        at org.hibernate.validator.metadata.MetaConstraint.validateConstraint(MetaConstraint.java:84) ~[hibernate-validator-4.2.0.Final.jar:4.2.0.Final]
        at org.hibernate.validator.engine.ValidatorImpl.validateConstraint(ValidatorImpl.java:452) ~[hibernate-validator-4.2.0.Final.jar:4.2.0.Final]
        at org.hibernate.validator.engine.ValidatorImpl.validateConstraintsForDefaultGroup(ValidatorImpl.java:397) ~[hibernate-validator-4.2.0.Final.jar:4.2.0.Final]
        at org.hibernate.validator.engine.ValidatorImpl.validateConstraintsForCurrentGroup(ValidatorImpl.java:361) ~[hibernate-validator-4.2.0.Final.jar:4.2.0.Final]
        at org.hibernate.validator.engine.ValidatorImpl.validateInContext(ValidatorImpl.java:313) ~[hibernate-validator-4.2.0.Final.jar:4.2.0.Final]
        at org.hibernate.validator.engine.ValidatorImpl.validate(ValidatorImpl.java:139) ~[hibernate-validator-4.2.0.Final.jar:4.2.0.Final]
        at org.springframework.validation.beanvalidation.SpringValidatorAdapter.validate(SpringValidatorAdapter.java:145) ~[spring-context-3.0.6.RELEASE.jar:3.0.6.RELEASE]
        at org.syncope.core.persistence.validation.entity.EntityValidationInterceptor.save(EntityValidationInterceptor.java:55) ~[EntityValidationInterceptor.class:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_26]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_26]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_26]
        at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_26]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621) ~[spring-aop-3.0.6.RELEASE.jar:3.0.6.RELEASE]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610) ~[spring-aop-3.0.6.RELEASE.jar:3.0.6.RELEASE]
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:65) ~[spring-aop-3.0.6.RELEASE.jar:3.0.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.0.6.RELEASE.jar:3.0.6.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:90) ~[spring-aop-3.0.6.RELEASE.jar:3.0.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.0.6.RELEASE.jar:3.0.6.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202) ~[spring-aop-3.0.6.RELEASE.jar:3.0.6.RELEASE]
        at $Proxy74.save(Unknown Source) ~[na:na]
        at org.syncope.core.workflow.ActivitiUserWorkflowAdapter.create(ActivitiUserWorkflowAdapter.java:216) ~[ActivitiUserWorkflowAdapter.class:na]
        at org.syncope.core.workflow.AbstractUserWorkflowAdapter.create(AbstractUserWorkflowAdapter.java:43) ~[AbstractUserWorkflowAdapter.class:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_26]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_26]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_26]
        at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_26]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:309) ~[spring-aop-3.0.6.RELEASE.jar:3.0.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) ~[spring-aop-3.0.6.RELEASE.jar:3.0.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) ~[spring-aop-3.0.6.RELEASE.jar:3.0.6.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110) ~[spring-tx-3.0.6.RELEASE.jar:3.0.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.0.6.RELEASE.jar:3.0.6.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202) ~[spring-aop-3.0.6.RELEASE.jar:3.0.6.RELEASE]
        at $Proxy80.create(Unknown Source) ~[na:na]
        at org.syncope.core.rest.controller.UserController...

_Original issue: http://code.google.com/p/syncope/issues/detail?id=226_

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on December 01, 2011 07:36:32_

**Status:** Started  
  **Owner:** chicchiricco

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on December 01, 2011 07:37:02_

This issue was closed by revision r1275 .

**Status:** Fixed
