### ISSUE TITLE
AES password chiper algoritm Exception

### ISSUE THREAD

**Issue by ilgrosso** [ilgrosso/oldSyncopeIdM#237]
_From [denis.si...@gmail.com](https://code.google.com/u/105548482992247672762/) on December 06, 2011 10:04:23_

What steps will reproduce the problem? 1. Configure parameter "password.cipher.algorithm" with "AES" value
2. Save settings
3. Create a new user What version of the product are you using? On what operating system? - Product rev: trunk,
- Operative System: x86_64 x86_64 GNU/Linux, 
- JVM: Java HotSpot(TM) 64-Bit Server VM (build 21.0-b17, mixed mode) Please provide any additional information below. ==> /opt/syncope/trunk/core/target/log/core-persistence.log \<==
09:59:07.492 ERROR org.syncope.core.persistence.beans.AbstractBaseBean - Could not encode password
java.security.InvalidKeyException: Illegal key size or default parameters
   at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1010) ~[na:1.7.0-ea]
   at javax.crypto.Cipher.implInit(Cipher.java:785) ~[na:1.7.0-ea]
   at javax.crypto.Cipher.chooseProvider(Cipher.java:848) ~[na:1.7.0-ea]
   at javax.crypto.Cipher.init(Cipher.java:1212) ~[na:1.7.0-ea]
   at javax.crypto.Cipher.init(Cipher.java:1152) ~[na:1.7.0-ea]
   at org.syncope.core.persistence.beans.user.SyncopeUser.encodePassword(SyncopeUser.java:490) ~[SyncopeUser.class:na]
   at org.syncope.core.persistence.beans.user.SyncopeUser.setPassword(SyncopeUser.java:288) ~[SyncopeUser.class:na]
   at org.syncope.core.rest.data.UserDataBinder.create(UserDataBinder.java:206) [UserDataBinder.class:na]
   at org.syncope.core.rest.data.UserDataBinder$$FastClassByCGLIB$$33c4cc9.invoke(<generated>) [cglib-2.2.jar:na]
   at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191) [cglib-2.2.jar:na]

Can you give me some information how to store password
with symmetric-key algorithm and how can I setup a connector
to retrive the clear text password?

Thanks,
Denis.

_Original issue: http://code.google.com/p/syncope/issues/detail?id=237_

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on December 06, 2011 01:22:03_

The error you are reporting above will be fixed with next release.

Please ask your questions to syncope-users@googlegroups.com.

**Labels:** -Priority-Medium Priority-High Milestone-Release-201112 Component-Logic Source-trunk

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on December 06, 2011 02:48:33_

**Status:** Started  
  **Owner:** chicchiricco

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on December 06, 2011 03:30:35_

This issue was closed by revision r1287 .

**Status:** Fixed
