### ISSUE TITLE
Error messages into user search tab

### ISSUE THREAD

**Issue by ilgrosso** [ilgrosso/oldSyncopeIdM#242]
_From [Massimil...@gmail.com](https://code.google.com/u/103012165050613820067/) on December 07, 2011 10:40:23_

What steps will reproduce the problem? 1. Go to user search tab under users tab
2. Click on search without select a search criteria
3. Error messages appears
4. Set a search criteria
5. Click on search
6. Error messages have not disappeared What is the expected output? What do you see instead? The correct way is that error messages disappeared.

_Original issue: http://code.google.com/p/syncope/issues/detail?id=242_

**Comment by ilgrosso** [comment]
_From [mdisabat...@gmail.com](https://code.google.com/u/101550733072735377085/) on December 07, 2011 03:16:20_

Error messages into user search tab have not disappeared because Syncope goes to exception, consequently the console are not refreshed.
This happens when search criteria is set with Filter Name = id.

11:58:08.859 ERROR org.syncope.console.SyncopeRequestCycleListener - Exception found
org.syncope.client.validation.SyncopeClientCompositeErrorException: {[GenericPersistence [org.hibernate.exception.SQLGrammarException]], }
	at org.syncope.client.validation.SyncopeClientErrorHandler.handleError(SyncopeClientErrorHandler.java:58) ~[syncope-client-0.7-SNAPSHOT.jar:na]
	at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:486) ~[spring-web-3.0.6.RELEASE.jar:3.0.6.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:443) ~[spring-web-3.0.6.RELEASE.jar:3.0.6.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:401) ~[spring-web-3.0.6.RELEASE.jar:3.0.6.RELEASE]
	at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:279) ~[spring-web-3.0.6.RELEASE.jar:3.0.6.RELEASE]
	at org.springframework.web.client.RestTemplate$$FastClassByCGLIB$$aa4e9ed0.invoke(<generated>) ~[cglib-2.2.jar:3.0.6.RELEASE]
	at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191) ~[cglib-2.2.jar:na]
	at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:688) ~[spring-aop-3.0.6.RELEASE.jar:3.0.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) ~[spring-aop-3.0.6.RELEASE.jar:3.0.6.RELEASE]
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:131) ~[spring-aop-3.0.6.RELEASE.jar:3.0.6.RELEASE]
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:119) ~[spring-aop-3.0.6.RELEASE.jar:3.0.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.0.6.RELEASE.jar:3.0.6.RELEASE]
	at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:621) ~[spring-aop-3.0.6.RELEASE.jar:3.0.6.RELEASE]
	at org.springframework.web.client.RestTemplate$$EnhancerByCGLIB$$8f85101f.postForObject(<generated>) ~[cglib-2.2.jar:3.0.6.RELEASE]

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on December 07, 2011 03:19:13_

**Labels:** -Priority-Medium Priority-High Milestone-Release-201112 Component-UI Component-Logic Source-trunk

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on December 07, 2011 05:11:41_

**Status:** Started

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on December 07, 2011 05:11:59_

**Owner:** chicchiricco

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on December 07, 2011 05:41:00_

This issue was closed by revision r1296 .

**Status:** Fixed
