### ISSUE TITLE
Exception adding user with a Long, Unique, Required Attribute

### ISSUE THREAD

**Issue by ilgrosso** [ilgrosso/oldSyncopeIdM#255]
_From [denis.si...@gmail.com](https://code.google.com/u/105548482992247672762/) on December 19, 2011 18:05:03_

What steps will reproduce the problem? 1. In the Schema Tab: Define a new User Attribute of Type Long, Required and Unique
2. In the User Tab: add a user and insert any value for the required Long attribute What is the expected output? What do you see instead? I can see an error occure and in catalina.out appearing this stack trace error (actually, it comes from core-rest.log):

java.lang.NullPointerException
        at org.syncope.core.persistence.beans.AbstractAttrValue.getValueAsString(AbstractAttrValue.java:110)
        at org.syncope.core.persistence.beans.AbstractAttr.getValuesAsStrings(AbstractAttr.java:81)
        at org.syncope.core.rest.data.AbstractAttributableDataBinder.fill(AbstractAttributableDataBinder.java:764)
        at org.syncope.core.rest.data.UserDataBinder.create(UserDataBinder.java:183)
        at org.syncope.core.rest.data.UserDataBinder$$FastClassByCGLIB$$33c4cc9.invoke(<generated>)
        at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191)
        at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:688)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:621)
        at org.syncope.core.rest.data.UserDataBinder$$EnhancerByCGLIB$$1ef97e04.create(<generated>)
        at org.syncope.core.workflow.activiti.Create.doExecute(Create.java:32)
        at org.syncope.core.workflow.activiti.AbstractActivitiDelegate.execute(AbstractActivitiDelegate.java:55)
        at org.activiti.engine.impl.delegate.JavaDelegateInvocation.invoke(JavaDelegateInvocation.java:34)
        at org.activiti.engine.impl.delegate.DelegateInvocation.proceed(DelegateInvocation.java:37)
        at org.activiti.engine.impl.delegate.DefaultDelegateInterceptor.handleInvocation(DefaultDelegateInterceptor.java:25)
        at org.activiti.engine.impl.bpmn.behavior.ServiceTaskJavaDelegateActivityBehavior.execute(ServiceTaskJavaDelegateActivityBehavior.java:49)
        at org.activiti.engine.impl.bpmn.behavior.ServiceTaskJavaDelegateActivityBehavior.execute(ServiceTaskJavaDelegateActivityBehavior.java:40)
        at org.activiti.engine.impl.bpmn.helper.ClassDelegate.execute(ClassDelegate.java:112)
        at org.activiti.engine.impl.pvm.runtime.AtomicOperationActivityExecute.execute(AtomicOperationActivityExecute.java:44)
        at org.activiti.engine.impl.interceptor.CommandContext.performOperation(CommandContext.java:76)
        at org.activiti.engine.impl.persistence.entity.ExecutionEntity.performOperationSync(ExecutionEntity.java:497)
        at org.activiti.engine.impl.persistence.entity.ExecutionEntity.performOperation(ExecutionEntity.java:492) What version of the product are you using? On what operating system? - Product rev: trunk, rev 1338
- Operative System: x86_64 x86_64 GNU/Linux, 
- JVM: Java HotSpot(TM) 64-Bit Server VM (build 21.0-b17, mixed mode)
- Oracle Database 10g Release 10.2.0.3.0 - 64bit Production Please provide any additional information below. Full stack strace and screenshot attached.

**Attachment:** [attribute_long.png catalina.out](http://code.google.com/p/syncope/issues/detail?id=255)

_Original issue: http://code.google.com/p/syncope/issues/detail?id=255_

**Comment by ilgrosso** [comment]
_From [denis.si...@gmail.com](https://code.google.com/u/105548482992247672762/) on December 19, 2011 09:56:33_

Converting the attribute type to String the problem diasppear.

**Comment by ilgrosso** [comment]
_From [fabio.ma...@gmail.com](https://code.google.com/u/109095430973973917901/) on December 20, 2011 00:50:44_

**Status:** Started  
  **Owner:** fabio.ma...@gmail.com

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on December 20, 2011 01:38:29_

This happens because a conversion pattern should be set for any type but String / Enum. Anyway, we are fixing the issue so that conversion pattern will not be mandatory anymore, but optional.

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on December 20, 2011 01:38:47_

**Labels:** Milestone-Release-201112 Component-Logic Source-branch-0_7_X

**Comment by ilgrosso** [comment]
_From [fabio.ma...@gmail.com](https://code.google.com/u/109095430973973917901/) on December 21, 2011 01:07:12_

**Status:** Fixed
