### ISSUE TITLE
Change attribute type

### ISSUE THREAD

**Issue by ilgrosso** [ilgrosso/oldSyncopeIdM#258]
_From [mdisabat...@gmail.com](https://code.google.com/u/101550733072735377085/) on December 22, 2011 17:09:17_

What steps will reproduce the problem? 1. Create a new User Schema attribute of type Double.
2. Create a new User.
3. Change User Schema attribute created previously.
4. Edit the user.

What is the expected output?
Edit user form.

What do you see instead?
Stacktrace

org.springframework.web.client.HttpServerErrorException: 500 Internal Server Error
     at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:77)
     at org.syncope.client.validation.SyncopeClientErrorHandler.handleError(SyncopeClientErrorHandler.java:47)
     at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:486)
     at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:443)
     at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:401)
     at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:199)
     at WICKET_org.springframework.web.client.RestTemplate$$FastClassByCGLIB$$aa4e9ed0.invoke(<generated>)
     at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191)
     at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:688)
     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
     at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:131)
     at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:119)
     at

_Original issue: http://code.google.com/p/syncope/issues/detail?id=258_

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on December 22, 2011 08:13:06_

**Labels:** Component-UI Milestone-Release-201112 Component-Logic Source-branch-0_7_X

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on December 22, 2011 08:13:48_

Changing schema type should not be allowed when attributes exist.

**Status:** Started  
  **Owner:** chicchiricco

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on December 23, 2011 00:56:00_

This issue was closed by revision r1346 .

**Status:** Fixed
