### ISSUE TITLE
User attribute schema with Unique constraint

### ISSUE THREAD

**Issue by ilgrosso** [ilgrosso/oldSyncopeIdM#259]
_From [mdisabat...@gmail.com](https://code.google.com/u/101550733072735377085/) on December 23, 2011 11:20:48_

What steps will reproduce the problem? 1. Create a new user attribute schema with Unique constraint
2. Create a new user
3. Update the user by assigning a role.

What is the expected output?
Updated user

What do you see instead?
Exception

java.lang.NullPointerException
	at org.syncope.core.rest.data.AbstractAttributableDataBinder.fill(AbstractAttributableDataBinder.java:483)
	at org.syncope.core.rest.data.UserDataBinder.update(UserDataBinder.java:277)
	at org.syncope.core.rest.data.UserDataBinder$$FastClassByCGLIB$$33c4cc9.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191)
	at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:688)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:621)
	at org.syncope.core.rest.data.UserDataBinder$$EnhancerByCGLIB$$a42a90ab.update(<generated>)
	at org.syncope.core.workflow.activiti.Update.doExecute(Update.java:34)
	at org.syncope.core.workflow.activiti.AbstractActivitiDelegate.execute(AbstractActivitiDelegate.java:55)

_Original issue: http://code.google.com/p/syncope/issues/detail?id=259_

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on December 23, 2011 02:31:46_

**Status:** Started  
  **Owner:** chicchiricco  
  **Labels:** Milestone-Release-201112 Source-branch-0_7_X Component-Logic

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on December 23, 2011 03:29:00_

This issue was closed by revision r1347 .

**Status:** Fixed

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on December 29, 2011 01:30:09_

Issue 265 has been merged into this issue.
