### ISSUE TITLE
DuplicateUniqueValue Error on Unique Derived Attribute

### ISSUE THREAD

**Issue by ilgrosso** [ilgrosso/oldSyncopeIdM#262]
_From [denis.si...@gmail.com](https://code.google.com/u/105548482992247672762/) on December 23, 2011 17:17:45_

What steps will reproduce the problem? 1. Define a Required, Unique Derived Attribute (Long)
2. Create one user with a value in the field
3. Create a second user with different value in the same field What is the expected output? What do you see instead? -  Second user created. Instead an Exception thrown. What version of the product are you using? On what operating system? - Product rev: trunk (1348)
- Operative System: x86_64 x86_64 GNU/Linux, 
- JVM: Java HotSpot(TM) 64-Bit Server VM (build 21.0-b17, mixed mode)
- Apache Tomcat 7.0.22 Please provide any additional information below. Stacktrace:

17:14:49.128 ERROR org.syncope.core.rest.controller.AbstractController - Exception thrown by REST methods
org.springframework.dao.DataIntegrityViolationException: Could not execute JDBC batch update; SQL [insert into UAttrUniqueValue (booleanValue, dateValue, doubleValue, longValue, stringValue, attribute_id, schema_name, id) values (?, ?, ?, ?, ?, ?, ?, ?)]; constraint [IDM.SYS_C009167]; nested exception is org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
        at org.springframework.orm.hibernate3.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:637) ~[spring-orm-3.0.6.RELEASE.jar:3.0.6.RELEASE]
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:102)

_Original issue: http://code.google.com/p/syncope/issues/detail?id=262_

**Comment by ilgrosso** [comment]
_From [denis.si...@gmail.com](https://code.google.com/u/105548482992247672762/) on December 23, 2011 08:29:06_

moreover: Caused by: java.sql.BatchUpdateException: ORA-00001: unique constraint (IDM.SYS_C009167) violated

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on December 23, 2011 09:48:13_

Syncope does not currently support UNIQUE constraint on derived schemas (see [1] for more details), so I guess that you are talking about a plain schema.

If you are on Oracle, you should take an additional step when deploying, as explained in [2]: you should use the Oracle version of mapping file (orm.xml) instead of standard one.

[1] https://groups.google.com/forum/#!topic/syncope-users/pJnoN2NtfsY [2] http://wiki.syncope-idm.org/index.php?title=GettingStarted/RunDeployment#Oracle

**Status:** Invalid
