### ISSUE TITLE
ORA-00972: identifier is too long error on a fresh install

### ISSUE THREAD

**Issue by ilgrosso** [ilgrosso/oldSyncopeIdM#263]
_From [denis.si...@gmail.com](https://code.google.com/u/105548482992247672762/) on December 27, 2011 17:11:39_

What steps will reproduce the problem? 1. Install Syncope with Oracle DB
2. Use Oracle orm mapping file as described in the wiki Getting Started Page
3. Startup tomcat on an empty oracle schema What is the expected output? What do you see instead? no error on startup logs. Some index creation error 

ORA-00972: identifier is too long

(oracle limit index and table name to 30 characters) What version of the product are you using? On what operating system? - Product rev: trunk (1354)
- Operative System: x86_64 x86_64 GNU/Linux, 
- JVM: Java HotSpot(TM) 64-Bit Server VM (build 21.0-b17, mixed mode)
- Apache Tomcat 7.0.22 Please provide any additional information below. 16:40:50.848 INFO  org.syncope.core.init.ContentLoader - Empty database found, loading default content
16:40:51.257 ERROR org.syncope.core.init.ContentLoader - Could not create index
java.sql.SQLException: ORA-00972: identifier is too long

        at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:113) ~[ojdbc14.jar:Oracle JDBC Driver version - "10.2.0.5.0"]
        at oracle.jdbc.driver.T2CConnection.checkError(T2CConnection.java:693) ~[ojdbc14.jar:Oracle JDBC Driver version - "10.2.0.5.0"]
        at oracle.jdbc.driver.T2CConnection.checkError(T2CConnection.java:612) ~[ojdbc14.jar:Oracle JDBC Driver version - "10.2.0.5.0"]
        at oracle.jdbc.driver.T2CStatement.executeForDescribe(T2CStatement.java:778) ~[ojdbc14.jar:Oracle JDBC Driver version - "10.2.0.5.0"]
        at oracle.jdbc.driver.T2CStatement.executeForRows(T2CStatement.java:971) ~[ojdbc14.jar:Oracle JDBC Driver version - "10.2.0.5.0"]
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1192) ~[ojdbc14.jar:Oracle JDBC Driver version - "10.2.0.5.0"]
        at oracle.jdbc.driver.OracleStatement.executeUpdateInternal(OracleStatement.java:1662) ~[ojdbc14.jar:Oracle JDBC Driver version - "10.2.0.5.0"]
        at oracle.jdbc.driver.OracleStatement.executeUpdate(OracleStatement.java:1631) ~[ojdbc14.jar:Oracle JDBC Driver version - "10.2.0.5.0"]
        at org.syncope.core.init.ContentLoader.load(ContentLoader.java:164) ~[ContentLoader.class:na]
        at org.syncope.core.init.ContentLoader$$FastClassByCGLIB$$be1a104e.invoke(<generated>) [cglib-2.2.jar:na]
        at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191) [cglib-2.2.jar:na]
        at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:688) [spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) [spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110) [spring-tx-3.0.7.RELEASE.jar:3.0.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) [spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
        at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:621) [spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
        at org.syncope.core.init.ContentLoader$$EnhancerByCGLIB$$4b513572.load(<generated>) [cglib-2.2.jar:na]
        at org.syncope.core.init.SpringContextInitializer.afterPropertiesSet(SpringContextInitializer.java:57) [SpringContextInitializer.class:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1479) [spring-beans-3.0.7.RELEASE.jar:3.0.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1419) [spring-beans-3.0.7.RELEASE.jar:3.0.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:518) [spring-beans-3.0.7.RELEASE.jar:3.0.7.RELEASE]

**Attachment:** [indexes.txt](http://code.google.com/p/syncope/issues/detail?id=263)

_Original issue: http://code.google.com/p/syncope/issues/detail?id=263_

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on December 29, 2011 01:16:47_

**Status:** Accepted  
  **Owner:** fabio.ma...@gmail.com  
  **Labels:** -Priority-Medium Priority-High Milestone-Release-201112 Component-Persistence Source-branch-0_7_X

**Comment by ilgrosso** [comment]
_From [fabio.ma...@gmail.com](https://code.google.com/u/109095430973973917901/) on December 29, 2011 01:17:14_

**Status:** Started

**Comment by ilgrosso** [comment]
_From [fabio.ma...@gmail.com](https://code.google.com/u/109095430973973917901/) on December 29, 2011 05:57:18_

**Status:** Fixed
