### ISSUE TITLE
NullPointerException changing a Required, Long, Unique User Schema Attribute

### ISSUE THREAD

**Issue by ilgrosso** [ilgrosso/oldSyncopeIdM#265]
_From [denis.si...@gmail.com](https://code.google.com/u/105548482992247672762/) on December 28, 2011 12:47:25_

What steps will reproduce the problem? 1. Define a schema attribute of type Long and with Unique Constraint
2. Insert a new user with the required, unique, long attribute
3. Save User
4. Try change the attribute with a different one What is the expected output? What do you see instead? Attribute changed. Insted an excpetion occured. What version of the product are you using? On what operating system? - Product rev: trunk (1354)
- Operative System: x86_64 x86_64 GNU/Linux, 
- JVM: Java HotSpot(TM) 64-Bit Server VM (build 21.0-b17, mixed mode)
- Apache Tomcat 7.0.22 Please provide any additional information below. Full Stack Trace attached.

 at org.syncope.core.rest.data.AbstractAttributableDataBinder.fill(AbstractAttributableDataBinder.java:482) ~[AbstractAttributableDataBinder.class:na]
        at org.syncope.core.rest.data.UserDataBinder.update(UserDataBinder.java:277) ~[UserDataBinder.class:na]
        at org.syncope.core.rest.data.UserDataBinder$$FastClassByCGLIB$$33c4cc9.invoke(<generated>) ~[cglib-2.2.jar:na]
        at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191) ~[cglib-2.2.jar:na]
        at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:688) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110) ~[spring-tx-3.0.7.RELEASE.jar:3.0.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
        at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:621) ~[spring-aop-3.0.7.RELEASE.jar:3.0.7.RELEASE]
        at org.syncope.core.rest.data.UserDataBinder$$EnhancerByCGLIB$$992a7e54.update(<generated>) ~[cglib-2.2.jar:na]
        at org.syncope.core.workflow.activiti.Update.doExecute(Update.java:34) ~[Update.class:na]

**Attachment:** [FullStackTrace.txt](http://code.google.com/p/syncope/issues/detail?id=265)

_Original issue: http://code.google.com/p/syncope/issues/detail?id=265_

**Comment by ilgrosso** [comment]
_From [chicchiricco](https://code.google.com/u/chicchiricco/) on December 29, 2011 01:30:09_

This issue was solved by release 0.7RC2: a couple of new IT tests have been added to source code so that every commit would cause this to be tested via Jenkins: take a look at [1], tests issue259 () and issue260 ().

Please update your POM's references; in case you already did so, please be sure that you are actually using new 0.7RC2 artifacts: in order to do so you can for instance remove your local maven repository (rm ~/.m2/repository/org/syncope) and rebuild your project from scratch.

[1] http://syncope.googlecode.com/svn/tags/syncope-0.7RC2/core/src/test/java/org/syncope/core/rest/SchemaTestITCase.java

**Status:** Duplicate  
  **Labels:** Milestone-Release-201112  
  **Mergedinto:** 259
